components:
  # Reusable path, query, header and cookie parameters
  parameters:
    IdParameter:
      in: path
      name: id
      required: true
      schema:
        type: number
        example: 1

    LimitParameter:
      in: query
      name: limit
      schema:
        type: number
        example: 10

    PageParameter:
      in: query
      name: page
      schema:
        type: number
        example: 1

    StatusParameter:
      in: query
      name: status
      schema:
        $ref: '#/components/schemas/StatusSchema'

    AccountTypeParameter:
      in: query
      name: type
      schema:
        $ref: '#/components/schemas/AccountTypeSchema'
