version: "3"
services:
  api_mysql:
    image: mysql:8.0.31-debian
    container_name: api_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=template_db
    ports:
      - 3306:3306
    volumes:
      - api_volume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
  api:
    image: yudimatsuguma/template_nodejs:1.0.0
    container_name: api
    environment:
      - DB_URL=mysql://root:password@api_mysql:3306/template_db
    ports:
      - 8080:8080
    depends_on:
      api_mysql:
        condition:
          service_healthy
volumes:
  api_volume:
    driver: local
