version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    depends_on:
      api_mysql:
        condition:
          service_healthy
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: always

  api_mysql:
    image: mysql:8.0.31-debian
    container_name: api_mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 12
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=template_db
    ports:
      - "3306:3306"
    volumes:
      - api_volume:/var/lib/mysql

volumes:
  api_volume:
    driver: local
